// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukmuuovxbrbtmrxubbzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbXV1b3Z4YnJidG1yeHViYnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NDAxODYsImV4cCI6MjA4NzUxNjE4Nn0.6U2mdE3S9fJa7D7oJ-RhUSf8iIuK6F9DQLqSIWY7y9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});